"""
This file automatically compares the outputs generated using AIM with
the current GMAP version. GMAP creates the outputs live while this file
is run, so it always compares the most recent version of GMAP with AIM
outputs.

The purpose of this comparison is to see/check that the outputs
generated by GMAP are (most likely!) correct. During development,
frequencies didn't match, and we could observe how large the differences
were. Wrongly-calculated frequencies had always a frequency that
differed by at least 0.1 cm-1.

We cannot be more strict in comparing values as we currently are, as we
would then be detecting float errors (both programs use float32s).
The observant would notice that not all frequencies are compared equally
strictly. The chosen limits are the closest that worked while developing
the tests. During development, both programs were altered such that
they showed how they arrived at the results, and the outcomes of
np.multiply(VEG found, map constants) were incredibly close. The fact
that some maps have larger errors is (most likely) due to how the
float errors (which mainly originate in electric
potential/field/gradient calculations) are propagated until the
frequency.
"""


# standard library imports
from pathlib import Path

# 3rd party lib imports
import numpy as np

# GMAP imports
import GMAP.src.tools.cmd_interface as GM_ci


def test_TDCTasumi_coups(tmp_path):
    core_test_frequencies("TDCTasumi", tmp_path, 0.0004)


def test_TDCKnoester_coups(tmp_path):
    core_test_frequencies("TDCKnoester", tmp_path, 0.0001)


def test_TCC_coups(tmp_path):
    core_test_frequencies("TCC", tmp_path, 0.0002, "_c")
    core_test_frequencies("TCC", tmp_path, 0.0002, "_nb")


def test_Tasumi_coups(tmp_path):
    core_test_frequencies("Tasumi", tmp_path, 0.0002)


def test_GLDP_coups(tmp_path):
    core_test_frequencies("GLDP", tmp_path, 0.0002)


def core_test_frequencies(mapname, tmp_path, limit, nameadd=""):
    # This runs GMAP to create the results
    if mapname in ("Tasumi", "GLDP"):
        base_mapname = "TDCTasumi"
    else:
        base_mapname = mapname
    curdir = Path(__file__).resolve().parent
    GM_ci.cmd_interface([
        "GMAP", "GEM", "run",
        str((curdir / "data/basic_parameters.txt").resolve()),
        "--ProteinAmide.coupling_choice", base_mapname,
        "--ProteinAmide.NN_coupling_choice", mapname,
        "--ProteinAmide.legacy_mode", "AIM",
        "--output_data", "ham\\;",
        "--output_directory", str(tmp_path.resolve()),
        "--log_directory", str(tmp_path.resolve())
    ])

    # Due to bug found in AIM, some results are calculated with a newer
    # version of the program
    nr = 2
    if mapname == "TCC":
        nr = 3

    if mapname == "TDCKnoester":
        fmapname = "TDCKrimm"
    else:
        fmapname = mapname

    # now, we must test these newly generated results against the
    # AIM-calculated frequencies to see if the map is indeed correct.
    hamnew = makeham((tmp_path / "hamiltonian.txt").resolve(), 145)
    fname = f"data/{fmapname}{nameadd}_AIM_V1-0-{nr}_Hamiltonian.txt"
    hamold = makeham((curdir / fname).resolve(), 145)

    # this way, if the two do not match, we automatically get printed where/why
    # they disagree.
    # The value of 0.0002 should be large enough to allow for float errors,
    # but small enough to catch everything else.
    oldcoups = hamold[np.triu_indices(145, k=1)]
    newcoups = hamnew[np.triu_indices(145, k=1)]

    assert bool(np.any(np.isnan(newcoups))) is False
    mismatch = np.where(np.abs(oldcoups - newcoups) > limit)[0]
    print(mismatch)
    print(oldcoups[mismatch])
    print(newcoups[mismatch])
    print(
        np.average(oldcoups - newcoups),
        np.average(np.abs(oldcoups - newcoups))
    )
    assert mismatch.shape == (0,)


def makeham(fname, n_singles):
    with open(fname, "r") as fhand:
        flatham = fhand.readline()
    flatham = flatham.split()
    # we have the final +1 as the frame number is still in front!
    if len(flatham) != (n_singles * (n_singles + 1)) / 2 + 1:
        raise ValueError(
            "warning! provided hamiltonian length doesn't match!")
    flatham = flatham[1:]
    squareham = np.zeros((n_singles, n_singles))
    squareham[np.triu_indices(n_singles, k=0)] = flatham
    squareham = squareham + squareham.T - np.diag(np.diag(squareham))
    return squareham
