"""
This file automatically compares the outputs generated using AIM with
the current GMAP version. GMAP creates the outputs live while this file
is run, so it always compares the most recent version of GMAP with AIM
outputs.

The purpose of this comparison is to see/check that the outputs
generated by GMAP are (most likely!) correct. During development,
frequencies didn't match, and we could observe how large the differences
were. Wrongly-calculated frequencies had always a frequency that
differed by at least 0.1 cm-1.

We cannot be more strict in comparing values as we currently are, as we
would then be detecting float errors (both programs use float32s).
The observant would notice that not all frequencies are compared equally
strictly. The chosen limits are the closest that worked while developing
the tests. During development, both programs were altered such that
they showed how they arrived at the results, and the outcomes of
np.multiply(VEG found, map constants) were incredibly close. The fact
that some maps have larger errors is (most likely) due to how the
float errors (which mainly originate in electric
potential/field/gradient calculations) are propagated until the
frequency.
"""


# standard library imports
from pathlib import Path

# 3rd party lib imports
import numpy as np

# GMAP imports
import GMAP.src.tools.CmdInterface as GM_CI


def test_Tokmakoff_freqs(tmp_path):
    core_test_frequencies("Tokmakoff", tmp_path, 0.0004)


def test_Skinner_freqs(tmp_path):
    core_test_frequencies("Skinner", tmp_path, 0.0005)


def test_Jansen_freqs(tmp_path):
    core_test_frequencies("Jansen", tmp_path, 0.0007)


def test_Cho_freqs(tmp_path):
    core_test_frequencies("Cho", tmp_path, 0.0004)


def test_Hirst_freqs(tmp_path):
    core_test_frequencies("Hirst", tmp_path, 0.0011)


def test_Torii_dips(tmp_path):
    # here, providing the freq map is not actually necessary. But for Jansen,
    # it is.
    core_test_dipoles("Tokmakoff", "Torii", tmp_path, 0.000002)


def test_Jansen_dips(tmp_path):
    # As the Jansen dipoles and frequencies go together, the program must
    # be instructed both along eachother, otherwise it will bug out.
    core_test_dipoles("Jansen", "Jansen", tmp_path, 0.000002)


def test_C_pos(tmp_path):
    core_test_positions("C", tmp_path, 0.000004)


def test_N_pos(tmp_path):
    core_test_positions("N", tmp_path, 0.000004)


def test_O_pos(tmp_path):
    core_test_positions("O", tmp_path, 0.000004)


def test_D_pos(tmp_path):
    core_test_positions("D", tmp_path, 0.000004)


def test_raman(tmp_path):
    core_test_raman("", tmp_path, 0.00004)


def core_test_frequencies(mapname, tmp_path, limit):
    # This runs GMAP to create the results
    curdir = Path(__file__).resolve().parent
    GM_CI.cmd_interface([
        "GMAP", "GEM", "run",
        str((curdir / "data/basic_parameters.txt").resolve()),
        "--AmideSC.frequency_map_choice", mapname,
        "--output_data", "ham\\;",
        "--output_directory", str(tmp_path.resolve()),
        "--log_directory", str(tmp_path.resolve())
    ])

    # now, we must test these newly generated results against the
    # AIM-calculated frequencies to see if the map is indeed correct.
    hamnew = makeham((tmp_path / "hamiltonian.txt").resolve(), 17)
    hamold = makeham(
        (curdir / f"data/{mapname}-freq_AIM_V1-0-2_Hamiltonian.txt").resolve(),
        17)

    # this way, if the two do not match, we automatically get printed where/why
    # they disagree.
    # The value of 0.0002 should be large enough to allow for float errors,
    # but small enough to catch everything else.
    assert bool(np.any(np.isnan(np.diag(hamnew)))) is False
    mismatch = np.where(abs(np.diag(hamold) - np.diag(hamnew)) > limit)[0]
    print(mismatch)
    print(np.diag(hamold)[mismatch])
    print(np.diag(hamnew)[mismatch])
    print(
        np.average(np.diag(hamold) - np.diag(hamnew)),
        np.average(np.abs(np.diag(hamold) - np.diag(hamnew)))
    )
    print((np.diag(hamold) - np.diag(hamnew))[mismatch])
    assert mismatch.shape == (0,)


def makeham(fname, n_singles):
    with open(fname, "r") as fhand:
        flatham = fhand.readline()
    flatham = flatham.split()
    # we have the final +1 as the frame number is still in front!
    if len(flatham) != (n_singles * (n_singles + 1)) / 2 + 1:
        raise ValueError(
            "warning! provided hamiltonian length doesn't match!")
    flatham = flatham[1:]
    squareham = np.zeros((n_singles, n_singles))
    squareham[np.triu_indices(n_singles, k=0)] = flatham
    squareham = squareham + squareham.T - np.diag(np.diag(squareham))
    return squareham


def core_test_dipoles(freqmapname, dipmapname, tmp_path, limit):
    # This runs GMAP to create the results
    curdir = Path(__file__).resolve().parent
    GM_CI.cmd_interface([
        "GMAP", "GEM", "run",
        str((curdir / "data/basic_parameters.txt").resolve()),
        "--AmideSC.frequency_map_choice", freqmapname,
        "--AmideSC.dipole_map_choice", dipmapname,
        "--output_data", "dip\\;",
        "--output_directory", str(tmp_path.resolve()),
        "--log_directory", str(tmp_path.resolve())
    ])
    dipnew = read_dippos((tmp_path / "dipoles.txt").resolve(), 17, 3)
    dipold = read_dippos(
        (curdir / f"data/{dipmapname}-dip_AIM_V1-0-2_Dipoles.txt").resolve(),
        17, 3)
    core_compare_dippos(dipold, dipnew, limit)


def core_test_positions(atom, tmp_path, limit):
    # This runs GMAP to create the results
    curdir = Path(__file__).resolve().parent
    GM_CI.cmd_interface([
        "GMAP", "GEM", "run",
        str((curdir / "data/basic_parameters.txt").resolve()),
        "--AmideSC.pos_choice", atom,
        "--AmideSC.legacy_mode", "AIM",
        "--output_data", "pos\\;",
        "--output_directory", str(tmp_path.resolve()),
        "--log_directory", str(tmp_path.resolve())
    ])
    dipnew = read_dippos((tmp_path / "positions.txt").resolve(), 17, 3)
    dipold = read_dippos(
        (curdir / f"data/{atom}-pos_AIM_V1-0-2_AtomPos.txt").resolve(),
        17, 3)
    core_compare_dippos(dipold, dipnew, limit)


def core_test_raman(fbonus, tmp_path, limit):
    # This runs GMAP to create the results
    curdir = Path(__file__).resolve().parent
    GM_CI.cmd_interface([
        "GMAP", "GEM", "run",
        str((curdir / "data/basic_parameters.txt").resolve()),
        "--output_data", "ram\\;",
        "--output_directory", str(tmp_path.resolve()),
        "--log_directory", str(tmp_path.resolve())
    ])
    dipnew = read_dippos((tmp_path / "raman_tensor.txt").resolve(), 17, 6)
    dipold = read_dippos(
        (curdir / f"data/Raman{fbonus}_AIM_V1-0-2_RamanTensor.txt").resolve(),
        17, 6)
    core_compare_dippos(dipold, dipnew, limit)


def core_compare_dippos(oldfile, newfile, limit):
    mismatch = np.where((oldfile - newfile) > limit)
    assert bool(np.any(np.isnan(newfile))) is False
    print(mismatch)
    print(oldfile[mismatch[0], mismatch[1]])
    print(newfile[mismatch[0], mismatch[1]])
    assert mismatch[0].shape == (0,)


def read_dippos(fname, n_singles, n_cols):
    with open(fname, "r") as fhand:
        flatarr = fhand.readline()
    flatarr = flatarr.split()
    # we have the final +1 as the frame number is still in front!
    if len(flatarr) != (n_singles * n_cols) + 1:
        raise ValueError(
            "warning! provided file length doesn't match!")
    flatarr = np.array(flatarr[1:], dtype=np.float32)
    # we have to transpose, as the file lists all xs first, then al ys and zs.
    squarearr = flatarr.reshape((n_cols, n_singles)).T
    return squarearr
