"""Main code file for water map.

Also is the template/explanation for all that a map can hand directly to
GMAP. Of course, more functions are allowed, and these files can import
other custom python files stored in the same directory (or a directory
therein) as this file.

how about adding these?
 - post_init()
 - pre_run()  # just before per-frame loop
 - pre_frame()
 - post_frame()
 - post_run()

 - calculate_freq()
 - calculate_dipole()
"""

# GMAP imports
import GMAP.src.tools.constants as GM_Con

# Import System Reader for additional functionality
import GMAP.src.tools.SystemReader as GM_SR
import GMAP.src.tools.DefaultMapFunctions as GM_DMF


# A function to adjust the oscillators found for this map. Gets a list
# of oscillators, and is supposed to return a list of oscillators.
# For example, this function could remove some of the oscillators for
# some reason, and return the rest.
def GM_adjust_oscillators(Map, Syst, oscillator_list):
    """Makes the necessary changes to the list of oscillators.

    The program finds all oscillators mathing the instructions from
    core.txt. However, there is no way for the program to avoid double
    counting symmetrical groups (like the cystbridge mockup example).
    If a map knows its group is symmetrical, this function can be
    designed to only return half of the inputs.

    Another possible use is for the code of the map to get to know its
    oscillators. When all oscillators are passed through this function,
    the (global) atom number of the first atom of this group (for
    example) can be linked to a specific property the group might need
    to know. This might be useful if a map needs to cover two very
    similar oscillators.

    .. note::
        This function is called separately for each struct that the map
        defines. So take into account that the function could be called
        multiple times within a single simulation!

    Parameters
    ----------
    Files : :class:`~GMAP.src.tools.FileHandler.FileLocations`
        Contains all currently known paths and other file-related
        properties.
        Has to be updated after RunPars is finalized.
    Printer : :class:`~GMAP.src.tools.PrintTools.Printer`
        The object that allows to cleanly log and print during runtime,
        and handle errors.
    Map : :class:`~GMAP.src.tools.MapReader.Map`
        The object that stores everything the program currently knows
        about this map.
    Syst : :class:`~GMAP.src.tools.SystemReader.System`
        The object that stores everything the program currently knows
        about the system being treated (names, numbers, types, masses,
        charges of all atoms, for example)
    oscillator_list : list of :class:`~GMAP.src.tools.SystemReader.Oscillator`
        All oscillators belonging to a single struct of this map.

    Returns
    -------
    oscillator_list : list of :class:`~GMAP.src.tools.SystemReader.Oscillator`
        All oscillators belonging to a single struct of this map.
    """

    oscillator_list_adjusted = []
    for oscillator in oscillator_list:
        oscillator_list_adjusted.append(oscillator)
        # TLC Double check this line
        oscillator_list_adjusted.append(GM_SR.Oscillator(
            Syst,
            [oscillator.used_atoms[0], *oscillator.used_atoms[2:0:-1]],
            Map))
        # oscnew=oscillator_list_adjusted[-1]
        # oscnew.used_atoms = [
        #     oscillator.used_atoms[0],*oscillator.used_atoms[2:0:-1]]
        # oscnew.electrostatic_atoms = [oscnew.used_atoms[1]]
    return oscillator_list_adjusted


# A place to do further initialization if a map requires it. Think of
# things like building further lookup tables, for instance.
# (for AmideBB - find neighbours!)
def GM_post_init(Map, Syst):
    def calculate_frequency(Map, Syst, osc):
        freq = calc_frequency(Map, Syst, osc)
        osc.freq = freq
        return freq

    calc_frequency = GM_DMF.get_calculate_frequency(Map)
    Map.code.GM_calculate_frequency = calculate_frequency
    return


# returns the dipole position and vector for osc. To be used during a
# frame - must be fast.
# A map creator can write this function themselves, or let it be automatically
# generated by GEM during runtime

def GM_get_dipole_mag(Map, Syst, osc):
    # The value of mug was not given in Skinners paper
    # it was shared as private communication
    mug = 0.18749  # (in atomic units).

    # We need to know the frequency prediced for the OH for this map
    freq = osc.freq

    # The fields in the core of GEM are using Ångström, we need bohr for the
    # map
    E = osc.VEGout[0, 1] * GM_Con.bohr2ang ** 2
    return (
        (0.7112 + 75.59 * E) * mug  # mu_i
        * (0.1934 - 0.175e-5 * freq)  # x_i
        * (1.611 + 5.893e-4 * freq)  # p_i
    )
